### PR TITLE
Move most function to autoload directory

### PR DESCRIPTION
**Pull request by bruhtus**
To decrease startuptime, it's better to load only a few necessary
function, in this case is `s:BufstopAppend()`,
`s:BufstopGlobalAppend()`, and `s:TimeoutFiddle()` function to append
bufstop history. Other function can be called using autoload function.

### CODE REVIEW

**Comment by bruhtus** [comment]
Also, it would be great if we can add modified symbol like `:ls` does. I'm still not sure how to split `ls` output, can we remove only the buffer number rather than the entire left side?

**Comment by mihaifm** [comment]
Thanks for the interest, I'll give this a test when I have some time. Although I have to say I'm a fan of the single file simplicity, I often just copy paste it to a Linux box when I'm lazy :)

I'll also check if we can add the modifier symbols, I can't remember why I left those out.

**Comment by bruhtus** [comment]
@mihaifm yeah, sometimes I also like a single file but if it was more than one file, I usually make a shell script to download all those file 😂

Recently I learn about autoload function and how useful it is to make startuptime faster, so I thought "maybe I can make this awesome plugin faster if I moved most of the function into autoload directory?" and that's why I did this. For someone who use SSD, the difference is not really noticeable, but for someone who use HDD, it think the difference would be noticeable.

But then again, the choice is yours. I just want to inform you that you can make this awesome plugin faster by using autoload function.

**Comment by mihaifm** [comment]
I added buffer indicators and flags: https://github.com/mihaifm/bufstop/commit/90ef222740d8dcd2241ea9bbbe6a4742c3137428, thanks for the suggestion.

**Comment by mihaifm** [comment]
Closing this pull request for now, I may do some code refactoring at a later date and include these changes.

**Pull request closed without merging**
